// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsYpgz03S3_IlxGv4_mLvPocqnIAEKdcA',
    appId: '1:31960149910:web:05b241e0a76a23a25e37b7',
    messagingSenderId: '31960149910',
    projectId: 'kit-store-start',
    authDomain: 'kit-store-start.firebaseapp.com',
    storageBucket: 'kit-store-start.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi52cq9DoFj9JyYWnVAvNAtKj4XNB3FaA',
    appId: '1:31960149910:android:71b704dde5cf596e5e37b7',
    messagingSenderId: '31960149910',
    projectId: 'kit-store-start',
    storageBucket: 'kit-store-start.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWNSwryOKVKUG4KIBxWoxBe9jpbSRPFRU',
    appId: '1:31960149910:ios:cf2deefae9f5e8145e37b7',
    messagingSenderId: '31960149910',
    projectId: 'kit-store-start',
    storageBucket: 'kit-store-start.firebasestorage.app',
    iosBundleId: 'com.example.kitStoreStart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWNSwryOKVKUG4KIBxWoxBe9jpbSRPFRU',
    appId: '1:31960149910:ios:cf2deefae9f5e8145e37b7',
    messagingSenderId: '31960149910',
    projectId: 'kit-store-start',
    storageBucket: 'kit-store-start.firebasestorage.app',
    iosBundleId: 'com.example.kitStoreStart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsYpgz03S3_IlxGv4_mLvPocqnIAEKdcA',
    appId: '1:31960149910:web:6a61c65a213701b25e37b7',
    messagingSenderId: '31960149910',
    projectId: 'kit-store-start',
    authDomain: 'kit-store-start.firebaseapp.com',
    storageBucket: 'kit-store-start.firebasestorage.app',
  );
}
